collections:
  m:
    output: true
    permalink: /m/:path/
  m_redirects:
    output: true
    permalink: /m/:path/
  blog:
    output: true
    permalink: /blog/:path

defaults:
  - scope:
      path: ""
      type: m
    output: true
    values:
      layout: maerke
      type: maerke
  - scope:
      path: ""
      type: blog
    output: true
    values:
      layout: blogpost
      type: blogpost
      image_stock: diary

future: true

paymentsSiteUrl: "https://salg.mærkelex.dk"
defaultShippingPrice: 35
internationalShippingPrice: 55

shippingCountries:
- Danmark
- Sverige
- Norge
- Deutschland
- Føroyar
